
export const AGREGAR_TAREA = "AGREGAR_TAREA"
export const ELIMINAR_TAREA = "ELIMINAR_TAREA"
export const BOOL_ACTUALIZAR = "BOOL_ACTUALIZAR"
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA"
export const OBTENER_TAREA_SELECCIONADA = "OBTENER_TAREA_SELECCIONADA"
export const OBTENER_CONTENIDO = "OBTENER_CONTENIDO"
export const ORDENAR_LISTA_FECHA = "ORDENAR_LISTA_FECHA"
export const RECUPERAR_LISTA = "RECUPERAR_LISTA"

export const ASIGNAR_USUARIO = "ASIGNAR_USUARIO"






